version: 0.2

env:
  variables:
    TEMPLATE_DIR: templates

phases:
  install:
    commands:
      - chmod +x scripts/*.sh

  pre_build:
    commands:
      - echo "Running validate..."
      - bash scripts/validate.sh

  build:
    commands:
      - echo "Running template packager..."
      - bash scripts/template_packager.sh
      - echo "Running deployer..."
      - bash scripts/deploy.sh

  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - templates/main.yaml
